project_name: automock

before:
  hooks:
    - go mod tidy

builds:
  - id: automock
    main: ./cmd/auto-mock
    binary: automock
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - id: default
    builds: [automock]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

brews:
  - name: automock
    repository:
      owner: hemantobora
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: hemantobora@gmail.com
    directory: Formula
    homepage: "https://github.com/hemantobora/auto-mock"
    description: "AutoMock CLI – generate & deploy MockServer infra"
    commit_msg_template: "chore(brew): update {{ .FormulaName }} to {{ .Tag }}"
    license: "MIT"
    install: |
      bin.install "automock"
    test: |
      system "#{bin}/automock", "--version"
