# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Automock < Formula
  desc "AutoMock CLI – generate & deploy MockServer infra"
  homepage "https://github.com/hemantobora/auto-mock"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/hemantobora/auto-mock/releases/download/v0.0.1/automock_0.0.1_darwin_amd64.tar.gz"
      sha256 "d1756ef279595c952b40380acc5162874d573b1cbae102dac44bd238329576ac"

      def install
        bin.install "automock"
      end
    end
    on_arm do
      url "https://github.com/hemantobora/auto-mock/releases/download/v0.0.1/automock_0.0.1_darwin_arm64.tar.gz"
      sha256 "08e014aca76726b66d2969edf78a6d1e9b1959e336971e14234a624bc3c49a7b"

      def install
        bin.install "automock"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v0.0.1/automock_0.0.1_linux_amd64.tar.gz"
        sha256 "c378659d6fd814a57b83a9b6bbad17edbddd49eeea381d67f67f0905a734b427"

        def install
          bin.install "automock"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hemantobora/auto-mock/releases/download/v0.0.1/automock_0.0.1_linux_arm64.tar.gz"
        sha256 "14f436ae73784ba10975789addbdbebd095c0dddeb34ea027a888d78cf5f60bf"

        def install
          bin.install "automock"
        end
      end
    end
  end

  test do
    system "#{bin}/automock", "--version"
  end
end
